/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type Problem = {
    /**
     * URI reference that identifies the problem type, per RFC7807.
     */
    type?: string;
    /**
     * Short, human-readable summary of the problem type.
     */
    title: string;
    /**
     * HTTP status code generated by the origin server.
     */
    status: number;
    /**
     * Human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * Stable machine code (e.g., mime_not_allowed, cross_tenant_source, job_terminal, rate_limited)
     */
    code?: string;
    /**
     * Correlates server logs for this request. Also returned in X-Correlation-Id header.
     */
    correlationId?: string;
};

